### ISSUE TITLE
gh-pages branch website is not mobile responsive

### ISSUE THREAD

**Issue by sudheesh001** [Microsoft/extendvs#15]
![screen shot 2015-06-17 at 01 19 00](https://cloud.githubusercontent.com/assets/4545925/8192884/dadaad54-148e-11e5-980e-0749a589de9c.png)

The top black bar is mobile responsive and sticks to the width of the screen but the page as a whole isn't mobile responsive and any movements to the left / right (horizontal scroll) result in the breaking of the top Nav bar too.

I think a really good choice would be to show the contents as follows in the mobile view
```
- Write your own tools for visual studio
- Visual Studio Gallery
- Visual Studio Extensibility Resources
- Community Extensions
- Contribute
```

**Comment by ExtendVS** [comment]
@sudheesh001 thanks for letting me know. I'm looking into that.

**Comment by bertique** [comment]
We've moved all content from the gh-pages branch to readme files in the master repo

https://github.com/Microsoft/extendvs/blob/master/CommunityExtensions.md

Thanks!
