### ISSUE TITLE
Visual Studio gallery breaks down when I'm logged in

### ISSUE THREAD

**Issue by dg9ngf** [Microsoft/extendvs#20]
I have registered a new Microsoft account a few days ago and wanted to upload an extension I made for Visual Studio. At first I noticed that after filling out the submit form I received an error message with a ticket UUID. After a while I found out that I cannot even access any of the extension pages while I'm logged in. As soon as I log out, everything's fine. When I'm back in, I keep getting different UUIDs every time I access a page or want to upload my extension.

One of the IDs is "aa642bd4-8eb6-4098-b048-2c4bba720d74".

[Already posted in the forum](https://social.msdn.microsoft.com/Forums/en-US/9e7a33b6-32c5-4fce-a619-afa0a5dea299/visual-studio-gallery-breaks-down-when-im-logged-in?forum=msdnfeedback) and [here](https://social.msdn.microsoft.com/Forums/de-DE/db04f560-c66e-4cb2-bafd-a6631e1f0e7d/fehler-beim-upload-einer-extension?forum=msdngenerelle_fragende&prof=required)

**Comment by bertique** [comment]
Issue resolved in the forum

https://social.msdn.microsoft.com/Forums/en-US/9e7a33b6-32c5-4fce-a619-afa0a5dea299/visual-studio-gallery-breaks-down-when-im-logged-in?forum=msdnfeedback
