### ISSUE TITLE
How to get the assigned rule set programmatically

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/extendvs#27]
If you assign a rule set in a project's Properties Window, how can you get that value programmatically? Meaning, I want to open .csproj file and get the value for CodeAnalysisRuleSet. This would be for all configurations.

Any help is appreciated.

**Comment by bertique** [comment]
Hi @shaggygi , take a look at our Gitter rooms for VS extensibility and project system. Those would be a great place to ask these questions:
- https://gitter.im/Microsoft/extendvs
- https://gitter.im/Microsoft/VSProjectSystem

**Comment by shaggygi** [comment]
Thanks for the reference @bertique.  I added a question on that project and will update here if there is a solution.  I closed this issue for now.
