### ISSUE TITLE
Microsoft.VisualStudio.Settings.15.0: ExternalSettingsManager.CreateForApplication() can not load assembly Microsoft.VisualStudio.RegDetour

### ISSUE THREAD

**Issue by MikhailTymchukDX** [Microsoft/extendvs#38]
Hi,

I have a problem with [Microsoft.VisualStudio.Settings.15.0](https://www.nuget.org/packages/Microsoft.VisualStudio.Settings.15.0/15.0.25824-RC) package.

When I try to load settings with [`ExternalSettingsManager.CreateForApplication(devenvPath);`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.settings.externalsettingsmanager.aspx) call, an exception is thrown:

![image](https://cloud.githubusercontent.com/assets/17080984/21380370/de1c9956-c765-11e6-8009-b73551a51eb1.png)

How to fix it?

**Comment by AlexEyler** [comment]
You'll need to grab the [RegDetour package](https://www.nuget.org/packages/Microsoft.VisualStudio.RegDetour/) as well.
