### ISSUE TITLE
VSCT - Token replace on build support

### ISSUE THREAD

**Issue by dazinator** [Microsoft/extendvs#47]
In `vsct` files, it's common to use symbols like package GUID:

```

 <Symbols>
    <!-- This is out managed package guid. -->
    <GuidSymbol name="PackageGuidString" value="{A4F9D880-9492-4072-8BF3-2B5EEEDC9E68}" />

    <GuidSymbol name="guidDebugTargetHandlerPackage" value="{6e87cfad-6c05-4adf-9cd7-3b7943875b7c}">
      <IDSymbol name="DebugTargetMenuControllerGroup" value="0x1000" />
      <IDSymbol name="DebugTargetMenuControllerFooterGroup" value="0x2000" />

    </GuidSymbol>

```

Often these same values are declared as constants in the code somewhere:

```
 [Guid(VsPackage.PackageGuid)]
    public sealed class VsPackage : Package
    {

```

If the value of a symbol / guid changes, you are having to update / maintain the value in two places - i.e in the code, and manually in the vsct file.

It would be better if we could use tokens in t he vsct file that could be substituted on build.

One suggestion might be to use an attribute on the package, to expose tokens for substitution - i.e:

```

    [ProvideVsctToken("PackageGuid", VsPackage.PackageGuid)]
    [Guid(VsPackage.PackageGuid)]
    public sealed class VsPackage : Package
    {


```

Then in the vsct file:

```

 <GuidSymbol name="PackageGuidString" value="{%PackageGuid%}" />
```

On build, an msbuild task could discover the attributes and perform the substitution.

**Comment by dazinator** [comment]
I'll create a nugget package to do this. Idea is:

NuGet package will add a `targets` file to your project.
Targets file will override `VSCTCompileDependsOn`, to inject its own msbuild target that runs prior to VSCT compilation

```
  <VSCTCompileDependsOn>$(VSCTCompileDependsOn);ReplaceVsctTokens</VSCTCompileDependsOn>

```

Targets file will include the `ReplaceVsctTokens` target, that will do the grunt work.

NuGet package will also add a reference to the project, to an assembly containing the custom attribute - `[ProviceVsctToken]`. I'll compile this lib for .NetStandard.

The ReplaceVsctTokens target, will reflect on the output assembly to find these attributes. For any it finds, it will perform a token substitution in any VSCT files.

That's the plan.

**Comment by dazinator** [comment]
Thinking about it further, this syntax is probably not the best:

```
<GuidSymbol name="PackageGuidString" value="{%PackageGuid%}" />

```

because once the value has been replaced, the token is lost from the source so can't be replaced on future builds. 

This is because I forgot the token replacement is happening on the actual source file.

Therefore, it would be better to match to a `GuidSymbol`'s by it's `name` and then just replace its value.

i.e 


```
 [ProvideVsctToken("Foo", VsPackage.PackageGuid)]
 public class VsPackage: Package {
```

```
 <GuidSymbol name="Foo" value="THIS WILL BE REPLACED" />
```

**Comment by dazinator** [comment]
Code here: https://github.com/dazinator/VsctTokenReplace
I'll close this once I have verified the approach works.

**Comment by yannduran** [comment]
The *Extensibility Tools* extension by Mads Kristensen approaches this problem the other way around. It views the VSCT file as the 'source of truth' and generates a C# file that contains constants that mirrors all of the guids and CommandIds from the VSCT.

To enable it (with the extension installed) you simply right-click the VSCT file and select *Enable Auto-Sync*
You can then use these values in your code.

**Comment by dazinator** [comment]
That's an interesting approach.. Thanks for pointing me to it !

To be honest, I hit a snag with my way round, because I first need to compile the assembly before I can reflect on it - to update the vsct source file. This mean, if you change a GUID in the code, then do a build, the vsct source file will then be updated, but the assembly containing the original vsct source file has already been generated in the process - so the newly modified vsctf file won't have any impact until the next build.

I could use Roslyn instead of reflection, to grab the c# attribute values and update the VSCT source file pre-build. If I did this, the built assembly would have the changes. But as it stands that's a lot of work and I am happy with this known limitation for the time being.

To be honest I might just switch to the MAds approach :-)

**Comment by dazinator** [comment]
Just tried out mads extension, and it works great.
The only problem I might encounter is if I had multiple VSCT files, sharing GUID's. For example if `menus.vsct` and `foobar.vsct` both used the same symbol guid "PackageGuid" - mads extension would generate two classes for that, and I am guessing the guid value would be duplicated. Meaning if I change the value in one VSCT file, I also have to remember to change it in the other?

To be honest I am not sure how common it is to have multiple VSCT files with shared symbols / guids. I am fairly new to VSIX development.

**Comment by dazinator** [comment]
Yep Mads has got this - works great. Thanks
