### ISSUE TITLE
What is the most efficient way to determine which project system "owns" a file

### ISSUE THREAD

**Issue by RobertvanderHulst** [Microsoft/extendvs#52]
In our project system we are "competing" for a file extension with another project system.
During installation we have made sure that our own project system has the highest priority so any file with that extension is opened by us first.
We have created a class that implements IVsTextViewListener, and in the VsTextViewCreated event we try to determine if the file that was opened is part of our project system, or part of the competitors project system.
When it belongs to the competitors project system we set the LanguageServiceID for the textlines to the language service of the competitor.
You can see that code in: 
[VsTextViewCreationListener.cs](https://github.com/X-Sharp/XSharpPublic/blob/master/VisualStudio/ProjectPackage/Editors/VsTextViewCreationListener.cs)
The IsVulcanFileNode method inside [EditorHelpers](https://github.com/X-Sharp/XSharpPublic/blob/master/VisualStudio/ProjectPackage/Editors/EditorHelpers.cs)  uses DTE to get the project item for the filename and then looks in which assembly the type was defined:

```
EnvDTE80.DTE2 dte = Microsoft.VisualStudio.Shell.Package.GetGlobalService(typeof(EnvDTE.DTE)) as EnvDTE80.DTE2;
var projectitem = dte.Solution.FindProjectItem(filename);

```

This works, but we were told (by Sam Harwell) that this is a slow way to do things, especially for large projects.
Our project system is based on MPF (we need support for WinForms and WPF as well, so cannot use CPS). 
Opening a document from the solution explorer or error list will go through the document manager. That is not a problem. However  files that are opened from the Find Results window or from the output window are not opened through the document manager, so they will always be opened with our language service, even if they are part of the competitors project system.

**Comment by olegtk** [comment]
If the file is open and you can get its IVsWindowFrame, the most efficient way is to just get its __VSFPROPID.VSFPROPID_Hierarchy and __VSFPROPID.VSFPROPID_ItemID properties. That should give you hierarchy/itemid uniquely identifying the file in the project system. See https://github.com/Microsoft/VSSDK-Extensibility-Samples/blob/master/Code_Sweep/C%23/VsPackage/ProjectUtilities.cs for a sample.

**Comment by justcla** [comment]
@Will Buik<mailto:wibu@microsoft.com>, can you help with this?

Justin

**Comment by will** [comment]
Sorry I don't think I can help with this :/

**Comment by KirillOsenkov** [comment]
Adding the right @willbuik

**Comment by WillBuik** [comment]
Sorry, I just saw this notification.  I am not sure, but @jviau might be able to help with this.

**Comment by KirillOsenkov** [comment]
also @davkean

**Comment by RobertvanderHulst** [comment]
@WillBuik. We are still using DTE. So if you have a better solution, then I would love to hear that.

**Comment by RobertvanderHulst** [comment]
I am in Redmond (VS Partner Summit, which starts tomorrow) right  now, so I can show Jacob what we are doing if that helps. I have most of Friday available, so let me know if that is a good idea

**Comment by jviau** [comment]
I am struggling to think of something better than DTE or IVsProject here, as they will be the only project-agnostic way to go from a file path to the IVsHierarchy of that project. Alternative to `DTE.Soution.FindProjectItem` you could walk the projects and call `IVsProject.IsDocumentInProject`. But that is probably what `FindProjectItem` already does. 

I would look into what @olegtk suggested. Maybe there is a way to go from `IVsTextView` to `IVsWindowFrame` and then you can fetch the hierarchy property.

**Comment by dpugh** [comment]
Given an IVsTextView, you should be able to use the following to get the project hierarchy, etc.

IVsTextLines vsTextLines;
vsTextView.GetBuffer(out vsTextLines);

IVsUserData vsUserData = vsTextBuffer as IVsUserData;

Guid VsBufferMoniker = new Guid(0x978A8E17, 0x4DF8, 0x432A, 0x96, 0x23, 0xD5, 0x30, 0xA2, 0x64, 0x52, 0xBC);
object moniker;
vsUserData.GetData(ref VsBufferMoniker, out moniker);

IVsRunningDocumentTable rdt = ServiceProvider.GlobalProvider.GetService(typeof(IVsRunningDocumentTable)) as IVsRunningDocumentTable;

uint itemID;
IVsHierarchy hierarchy;
IntPtr unkDocData;
uint cookie;
if (rdt.FindAndLockDocument((uint)(_VSRDTFLAGS.RDT_NoLock), moniker as string,
                            out hierarchy, out itemID, out unkDocData, out cookie)) &&
    (unkDocData != IntPtr.Zero))
    {
        Marshal.Release(unkDocData);
        ...

**Comment by RobertvanderHulst** [comment]
@dpugh, Thanks for the hints. I will give this a try, and I will let you know if this works.
And you expect that this will be a lot faster then EnvDTE ?

**Comment by davkean** [comment]
Yes significantly, FindProjectItem searches the entire solution for a given file - can't speak for other project types, but managed types that is really, really expensive.

**Comment by RobertvanderHulst** [comment]
@dpugh. Thanks that helped. I ended up doing a call to  hierarchy.GetProperty(itemID, (int)__VSHPROPID8.VSHPROPID_DiagHubLanguage, out result); Our project system returns our development language, and that allows me to differentiate between the items from the other project system and ours. Even when the same file is shared between the 2 projects I can now see from which project node the file was opened.
