### ISSUE TITLE
Missing contract name on launch settings 

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/extendvs#59]
Hi,

I'm trying to replicate the Iris sample from ConcordExtensibilitySamples on my VS extension. After hitting the Start button for debug I'm getting this error:

![2017-09-11_15-51-17](https://user-images.githubusercontent.com/1881520/30289571-7f8f63b6-9724-11e7-8d0b-45541c47a44b.png)

Any hints on what is this? 
Plus I don't know what error log the error is referring to. If it's VS output window nothing is showing there.

Thanks!

**Comment by ashwanidv100** [comment]
Please check the error list for more detail- To display the Error List, click View / Error List, or CTRL+\+E.
Please show us the details from error list. And you can update your NuGet Packages by clicking on solution file and update NuGet or You can visit this URL to download and update: https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem/

**Comment by josesimoes** [comment]
@ashwanidv100 I don't get any error listed in the Error List window. This is both on the VS experimental instance and the VS window running the project system VSIX.

Also I'm already referencing v15.3.224 of the Project system NuGet package.

In the mean time I believe I've past this on by adding this to the targets file of the project:
`<ProjectCapability Include="LaunchProfiles" />`
and 
`<ProjectCapability Include="AppDesigner" />`

I'm closing this one and reopen if needed. 
Thanks!
